CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_ON_START=y
CONFIG_ZMK_BACKLIGHT_BRT_START=40
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_INDICATOR_LED_WIDGET=y
CONFIG_INDICATOR_LED_SHOW_BATTERY_ON_BOOT=y
CONFIG_INDICATOR_LED_SHOW_CRITICAL_BATTERY_CHANGES=y
CONFIG_INDICATOR_LED_SHOW_BLE=y
