manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # <--- v0.2에서 main으로 변경
      import: app/west.yml
  self:
    path: config
